<?php
/**
 * @file
 * Added intercassa payment method.
 */

define('COMMERCE_INTERKASSA_IK_FORM_HANDLER', 'https://sci.interkassa.com/');

/**
 * Implements hook_menu().
 */
function commerce_interkassa_menu() {
  $items['checkout/%commerce_order/payment/status'] = array(
    'title'           => 'Payment status',
    'page callback'   => 'commerce_interkassa_payment_status',
    'page arguments'  => array(1),
    'access callback' => 'commerce_interkassa_payment_check_data',
    'file'            => 'commerce_interkassa.pages.inc',
  );
  return $items;
}

/**
 * Check request data.
 *
 * @return bool
 *   The accuracy of the data.
 */
function commerce_interkassa_payment_check_data() {
  $request_data = $_POST;
	
	$allowed_ip = array('85.10.225.99', '85.10.225.103');
  $valid_ip = in_array($_SERVER['REMOTE_ADDR'], $allowed_ip);
  if (!$valid_ip) {
		watchdog("commerce_interkassa", "Данные пришли с другого IP! REMOTE IP ADDRESS = " . $_SERVER['REMOTE_ADDR']);
		return FALSE;
	}
	
	$request_data_keys = array(
    'ik_co_id',
		'ik_am',
		'ik_inv_st',
		'ik_sign',
  );
  foreach ($request_data_keys as $request_data_key) {
    if (!isset($request_data[$request_data_key])) {
			commerce_interkassa_add_log('Параметр @param отсутствует! function commerce_interkassa_payment_check_data @post', array('@param' => print_r($request_data_key, 1), '@post' => print_r($request_data, 1)));
      return FALSE;
    } 
  }
	$settings = commerce_payment_method_instance_load('commerce_interkassa|commerce_payment_commerce_interkassa');
	
	if ($request_data['ik_co_id'] != $settings['settings']['shop_id']) {
		commerce_interkassa_add_log('Индификатор кассы не соответствует! function commerce_interkassa_payment_check_data @post', array('@param' => print_r($request_data_key, 1), '@post' => print_r($request_data, 1)));
      return FALSE;
	}
	
  return TRUE;
}

/**
 * Returns the default settings for the interkassa payment method.
 *
 * @return array
 *   The default settings for payment method.
 */
function commerce_interkassa_default_settings() {
  return array(
    'shop_id'      => '',
    'secret_key'   => '',
    'form_handler' => COMMERCE_INTERKASSA_IK_FORM_HANDLER,
    'log_enable'   => 1,
  );
}

/**
 * Payment method callback: payment settings page.
 *
 * @param array $settings
 *   Payment method settings.
 *
 * @return array
 *   Settings form.
 */
function commerce_interkassa_settings_form($settings = NULL) {
  $settings = (array) $settings + commerce_interkassa_default_settings();

  $form = array();
  $form['shop_id'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Shop ID'),
    '#description'   => t('Shop id from Interkassa account'),
    '#default_value' => $settings['shop_id'],
    '#required'      => TRUE,
  );

  $form['secret_key'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Secret key'),
    '#description'   => t('Secret key from shop'),
    '#default_value' => $settings['secret_key'],
    '#required'      => TRUE,
  );

  $form['form_handler'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Form handler'),
    '#description'   => t('Script processing forms of payment'),
    '#default_value' => $settings['form_handler'],
    '#required'      => TRUE,
  );

  $form['log_enable'] = array(
    '#type'          => 'checkbox',
    '#title'         => t('Enable log'),
    '#default_value' => $settings['log_enable'],
  );
  return $form;
}

/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_interkassa_commerce_payment_method_info() {
  return array(
    'commerce_interkassa' => array(
      'title'                => t('Interkassa payment'),
      'display_title'        => t('Interkassa'),
			'description'          => t('Cистема INTERKASSA представляет собой, так называемый «платежный шлюз». Доступны следующие методы оплаты: VISA, MasterCard, Альфаклик, Сбербанк, Российский банк, Единый кошелек, LiqPay, Perfect Money, Paxum, Telemoney, Платежные терминалы, Евросеть, Связной, Алло, Почта России, Юнистрим, Contact, Анелик, Лидер, МТС, Мегафон. 
Комиссия 0%. При оплате этим способом возможна доставка следующими способами: 1.Курьерской доставкой во все города России 2.Почтой России без наложенного платежа'),
      'active'               => TRUE,
      'terminal'             => TRUE,
      'offsite'              => TRUE,
      'offsite_autoredirect' => TRUE,
    ),
  );
}

/**
 * Payment method callback: submit form.
 */
function commerce_interkassa_submit_form($payment_method, $pane_values, $checkout_pane, $order) {
  $build = array();
  $info = theme('image', array(
    'path'       => drupal_get_path('module', 'commerce_interkassa') . '/images/logo.gif',
    'alt'        => t('Interkassa'),
    'title'      => t('Interkassa'),
    'attributes' => array('class' => 'logo-interkassa'),
  ));
	
	$build['interkassa_information'] = array(
      '#markup' => 'Cистема INTERKASSA представляет собой, так называемый «платежный шлюз». Доступны следующие методы оплаты: Терминалы оплаты, Мегафон, МТС, Единый Кошелек. <br />',
  );
		
  $build['print_receipt'] = array('#markup' => $info,'#prefix' => '<br />');
  return $build;
}

/**
 * Payment method callback: payment redirect form.
 */
function commerce_interkassa_redirect_form($form, &$form_state, $order, $payment_method) {
  global $user, $base_url;
  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
  $amount        = $order_wrapper->commerce_order_total->amount->value();
  $currency_code = $order_wrapper->commerce_order_total->currency_code->value();
	
	global $base_url;
  $status_url    = url($base_url . '/checkout/' . $order->order_id . '/payment/status', array('absolute' => TRUE));

  $form['#name']   = 'payment';
  $form['#action'] = $payment_method['settings']['form_handler'];

  $form['ik_co_id'] = array(
    '#type'  => 'hidden',
    '#value' => $payment_method['settings']['shop_id'],
  );
  $form['ik_am'] = array(
    '#type'  => 'hidden',
    '#value' => commerce_currency_amount_to_decimal($amount, $currency_code),
  );
  $form['ik_pm_no'] = array(
    '#type'  => 'hidden',
    '#value' => $order->order_id,
  );
  $form['ik_desc'] = array(
    '#type'  => 'hidden',
    '#value' => t('Buying on the site @sname', array('@sname' => $base_url)),
  );
  $form['ik_suc_u'] = array(
    '#type' => 'hidden',
    '#value' => url('checkout/' . $order->order_id . '/payment/return/' . $order->data['payment_redirect_key'], array('absolute' => TRUE)), 
  );
	$form['ik_pnd_u'] = array(
    '#type' => 'hidden',
    '#value' => url('checkout/' . $order->order_id . '/payment/return/' . $order->data['payment_redirect_key'], array('absolute' => TRUE)), 
  );
  $form['ik_fal_u'] = array(
    '#type' => 'hidden',
    '#value' => url('checkout/' . $order->order_id . '/payment/back/' . $order->data['payment_redirect_key'], array('absolute' => TRUE)), 
  );	
  $form['ik_ia_u'] = array(
    '#type'  => 'hidden',
    '#value' => $status_url,
  );
  $elements = array(
    'ik_fal_m',
    'ik_suc_m',
    'ik_pnd_m',
		'ik_ia_m',
  );

  foreach ($elements as $element) {
    $form[$element] = array(
      '#type'  => 'hidden',
      '#value' => 'POST',
    );
  }

  $form['submit'] = array(
    '#type'  => 'submit',
    '#value' => t('Pay'),
  );
	
	commerce_interkassa_add_log('Данные для отправки заказа @order_number в платежку: @request_data', array(
    '@order_number' => $order->order_id,
    '@request_data' => print_r($form, 1),
  ));
	
  return $form;
}

/**
 * Payment method callback: redirect form return validation.
 */
 /*
function commerce_interkassa_redirect_form_validate($order, $payment_method) {
  if ($_POST['ik_inv_st'] == 'success') {
    commerce_interkassa_add_log('Order number @order_number payment success.', array('@order_number' => $order->order_id));
    return TRUE;
  }
  commerce_interkassa_add_log('Order number @order_number payment fail.', array('@order_number' => $order->order_id));
  return FALSE;
}
*/
/**
 * Creates transaction.
 *
 * @param object $order
 *   Commerce order.
 */
function commerce_interkassa_create_transaction($order) {
  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);

  $transaction                = commerce_payment_transaction_new('commerce_interkassa', $order->order_id);
  $transaction->instance_id   = $order->data['payment_method'];
  $transaction->amount        = $order_wrapper->commerce_order_total->amount->value();
  $transaction->currency_code = $order_wrapper->commerce_order_total->currency_code->value();
  $transaction->status        = COMMERCE_PAYMENT_STATUS_SUCCESS;
  $transaction->message       = t('The payment has completed.');

  commerce_payment_transaction_save($transaction);
  commerce_interkassa_add_log('Order number @order_number transaction created.', array('@order_number' => $order->order_id));
}

/**
 * Write messages to the system log.
 *
 * @param string $message
 *   Message text.
 * @param array $variables
 *   Variables to replace placeholders.
 */
function commerce_interkassa_add_log($message, $variables = array()) {
  $payment_method = commerce_payment_method_instance_load('commerce_interkassa|commerce_payment_commerce_interkassa');
  $payment_method['settings'] = (array) $payment_method['settings'] + commerce_interkassa_default_settings();
  if ($payment_method['settings']['log_enable']) {
    watchdog('commerce_interkassa', $message, $variables);
  }
}
